spring:
  application:
    name: kafka-auth-demo
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9090/oauth2/jwks

logging:
  level:
    org.springframework.security: DEBUG
    com.delorenzodaniele.kafka_auth_demo.order.controller: DEBUG


